first_app/urls.py
from django.urls import path
from first_app import views


app_name = 'first_app'
urlpatterns = [

    path(r'',views.index, name='index'),
    path(r'about/',views.about, name='about'),
    path(r'login/',views.form, name='form'),
    path(r'postform/',views.postform, name='post_form'),
    path(r'other/', views.other, name='other'),

    # register url
    path(r'register/', views.register, name='register'),


    path(r'user_login/', views.user_login, name='user_login')


]

first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from first_app import views

urlpatterns = [

    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
    path(r'^logout/$',views.user_logout,name='logout')
]

first_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Topic(models.Model):

    top_name = models.CharField(max_length=220, unique=True)


    def __str__(self):
        return self.top_name


class WebPage(models.Model):
    top = models.ForeignKey(Topic, on_delete=models.CASCADE)
    url = models.URLField(unique=True)
    name = models.CharField(max_length=220,unique=True)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey(WebPage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)


class UserProfileInfos(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,blank=True,null=True)

    potfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics/', blank=True)


    def __str__(self):
        return self.user.userame

first_app/forms.py
from django import forms
from first_app.models import WebPage
from django.contrib.auth.models import User
from first_app.models import UserProfileInfos


# Email Form for register
class EmailForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)
    vmail = forms.EmailField(max_length=100, label='Confirm Email ')
    text = forms.CharField(widget=forms.Textarea)


    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['vmail']

        if email != vmail:
            raise forms.ValidationError("Email not Conformed")


# for post user
class PostForm(forms.ModelForm):

    class Meta:
        model = WebPage
        fields = ('top', 'url', 'name')

    def clean(self):
        all_clean = super().clean()
        return all_clean


# for profile user
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfo(forms.ModelForm):
    class Meta():
        model = UserProfileInfos
        fields = ('potfolio_site','profile_pic')

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Topic,AccessRecord,WebPage
from first_app.forms import EmailForm,PostForm, UserForm
from first_app.forms import UserProfileInfo

from django.contrib.auth import authenticate, login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    webpage_list = AccessRecord.objects.order_by('date')
    context = {'access_record':webpage_list, 'name':'amir mahdi rashvand', 'number':10000}
    template = 'index.html'
    return render(request, template, context )


def about(request):

    template = "first_app/about.html"
    message = "you are now beginner and 3 weeks after you are professional"
    return render(request, template, {'message':message})


def form(request):
    form = EmailForm()
    template = 'form.html'
    context = {'form':form}


    if request.method == 'POST':
        form = EmailForm(request.POST)

        if form.is_valid():
            print('name  : ' +form.cleaned_data['name'])
            print('email : '+ form.cleaned_data['email'])
            print('text  : '+ form.cleaned_data['text'])

    return render(request, template, context)


def postform(request):

    post_form = PostForm()
    template = 'post_form.html'
    context = {'post_form':post_form}


    if request.method == 'POST':
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            post_form.save(commit=True)
            # print('name  : ' +post_form.cleaned_data['top'])
            print('email : '+ post_form.cleaned_data['url'])
            print('text  : '+ post_form.cleaned_data['name'])
        else:
            print("form invalid")


    return render(request, template, context)


def other(request):
    return render(request, 'other.html')



#  ارور داریم برای لاگین دوباره قسمت ها رو ببین
# register form
def register(request):

    registerd = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfo(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=True)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registerd = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form  = UserProfileInfo()

    return render(request, 'registration.html', {'user_form':user_form,
                                                'profile_form':profile_form,
                                                 'registerd':registerd})



@login_required
def special(request):
    return HttpResponse("you are logged in")
# user logout
@login_required
def user_logout(request):
    logout(request)
    return HttpResponse(reverse('index'))
# user login
def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponse(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print("someone tried to login failed")
            print("username : {} and password {}".format(username,password))

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>
  </head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar w/ text</a>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'first_app:index'}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'first_app:register'}">register</a>
      </li>

      {% if user.is_authenticated %}
        <li><a href="{% url 'logout' %}">Logout
        </li>
      {% endif %}
    </ul>
    <span class="navbar-text">
      Navbar text with an inline element
    </span>
  </div>
</nav>
  <body>

    {% block content %}

    {% endblock %}

  </body>
</html>

templates/first_app/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>welcome</title>
  </head>
  <body>

    <h1> About </h1>
    {{ message }}

  </body>
</html>

templates/form.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Login</title>
  </head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">  <body>

  <body>


    <form class="login"  method="post">

      {{ form.as_p }}
      {% csrf_token %}

      <input class="btn btn-primary" type="submit" name="submit" value="submit">

    </form>

  </body>
</html>

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Welcome To My Blog</title>
  </head>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">  <body>




    <h1> Hello World </h1>

    {{ author }}


    <h1> {{ name|cut:'ali' }} </h1>
    <h1>{{number|add:"10"}}</h1>

    <p> This is my first blog </p>


    <h1><a href="{% url 'first_app:other' %}"> LINK TO OTHER  </a></h1>
<div class="djangotwo">
      <table  class="table table-dark">
    <thead>



      {% if access_record %}
      <tr>
        <th scope="col">Site Name</th>
        <th scope="col">Date</th>
      </tr>
    </thead>

    {% for acc in access_record %}
    <tbody>
      <tr>
        <td>{{ acc.name }}</td>
        <td>{{ acc.date }}</td>
      </tr>
    </tbody>
  {% endfor %}
  </table>
{% else %}
</div>
<p> Access Dosent exist </p>
{% endif %}


  </body>
</html>

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<div class="jumborton">

  <h1>Please Login</h1>

  <form class="{% url 'first_app:user_login' %}" method="post">

    {% csrf_token %}

    <label for="username ">username : </label>
    <input type="text" name="username" placeholder="">


    <label for="password ">password : </label>
    <input type="password" name="username" placeholder="">


    <input type="submit" name="" value="Login">


  </form>

</div>

{% endblock %}

templates/other.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    {% block title %} other {% endblock %}
  </head>
  <body>

{% block content %}
<h1>welcome to other </h1>

{% endblock %}
  </body>
</html>

templates/post_form.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>post</title>
  </head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">  <body>

  <body>


    <form class="post_form" method="post">

      {{ post_form.as_p }}
      {% csrf_token %}

      <input class="btn btn-primary" type="submit" name="submit" value="submit">

    </form>

  </body>
</html>

templates/registration.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}

<div class="jumpton">

  {% if registerd %}

    <h1>Thank you for registred</h1>

  {% else %}
    <h1>register here</h1>

    <form enctype="multipart/form-data" method="post">

      {% csrf_token %}

      {{ user_form.as_p }}
      {{ profile_form.as_p }}


      <input type="submit" name="" value="register">
    </form>

  {% endif %}

</div>

{% endblock %}